### PR TITLE
Some fixes to group creation

### PR DESCRIPTION
**Pull request by timreyn**
- Allow skipping certain group numbers. This allows e.g. one stage to go
  to lunch early, or come back from lunch late, while following the same
  group numbers as the other stages.

- Add a param for whether to use the stage color, rather than a generic
  "Group", rather than just doing it based on the number of rooms with a
  particular event.

- Allow adding groups without an activity already existing. The goal is
  to allow the script to encode the whole schedule, rather than needing
  to first set it in the GUI and then in a script.

- Correctly convert datetime literals to the venue timezone.

### CODE REVIEW

**Comment by timreyn** [comment]
@viroulep I'd appreciate it if you can review this! Want to make sure I'm not breaking anything you use.

(I'm creating 2 more pull requests as well, it's less important that you review those but definitely feel free!)

**Comment by timreyn** [comment]
Script using this (plus the other two PRs):
https://github.com/cubingusa/nats-scripts/blob/main/2024/build_schedule.cs

**Comment by viroulep** [comment]
Looks like some very interesting changes, I'll take a look tonight :)

**Comment by viroulep** [comment]
Looks really nice to me :)

The only change that could have an impact on my ongoing work is this part:
> Allow adding groups without an activity already existing. The goal is
to allow the script to encode the whole schedule, rather than needing
to first set it in the GUI and then in a script.

First of all I like the idea of being able to simply recreate the schedule from scratch!
How do you see this working with non WCA event activities (eg: lunches and so on)?
What if you end up having to adjust the duration of a round: how would you remove the existing groups/round, to make sure you don't duplicate the activities in the schedule?

I rely on the existing behavior to tell me if I have made a mistake with the starting/end time of a group; ideally I'd love an optional parameter to prevent the round activity creation if nothing matches, but if it's easy to remove/add a whole round in the schedule I can also make my scripts recreate everything from scratch (which I'd love in case someone accidentally mess something up on the WCA website).

**Comment by timreyn** [comment]
> Looks really nice to me :)
> 
> The only change that could have an impact on my ongoing work is this part:
> 
> > Allow adding groups without an activity already existing. The goal is
> > to allow the script to encode the whole schedule, rather than needing
> > to first set it in the GUI and then in a script.
> 
> First of all I like the idea of being able to simply recreate the schedule from scratch! How do you see this working with non WCA event activities (eg: lunches and so on)? What if you end up having to adjust the duration of a round: how would you remove the existing groups/round, to make sure you don't duplicate the activities in the schedule?
> 
For non-WCA event activities, I was just planning on doing those via the GUI, since they are a lot simpler and don't need groups.

For adjusting the duration of the round: I'm not planning on doing that :)

My plan is, over the next month until registration closes, keep running the scripts I'm writing over and over on the dev website, deleting and restarting anytime I need to (either by using the GUI, or a script, or via reloading the dev database). Then once registration closes, run create_schedule.cs (and every other script) exactly once on the production site. At that point, I will know that it works without needing to run it and undo it.

> I rely on the existing behavior to tell me if I have made a mistake with the starting/end time of a group; ideally I'd love an optional parameter to prevent the round activity creation if nothing matches, but if it's easy to remove/add a whole round in the schedule I can also make my scripts recreate everything from scratch (which I'd love in case someone accidentally mess something up on the WCA website).

I can add a parameter to keep the old behavior. Note that, in the current behavior, some mismatches would be allowed -- if the schedule has an event from 10:00-12:00, and you CreateGroups from 11:00-12:00, that would still be permitted. So it's not complete protection against that.

**Comment by timreyn** [comment]
I believe the parameter I added should address your comment. I'm going to go ahead and merge this so that I can keep moving, but please comment if you see any other issues or would like any other changes!

**Pull request merged**
